service: hello-serverless


frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev


functions:
  hello:
    handler: handler.hello

  add:
    handler: add.add
    events:
      - http:
          path: math/add
          method: post
          cors: true




