service: hello-serverless


frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  memorySize: 128
  timeout: 3


functions:
  hello:
    handler: handler.hello
    vpc:
      securityGroupIds:
        - sg-5096420d
      subnetIds:
        - subnet-60c3d36f
        - subnet-47fb9979
        - subnet-bbb6ede7

  add:
    handler: add.add
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: math/add
          method: post
          cors: true





